### PR TITLE
v0.1.2

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 282b086 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 282b08643126469a9c0813d484939c625fd16851 with merge d51a39b0ad1665c04ecead9ab148a5520dca139b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-hal/builds/339679295?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d51a39b0ad1665c04ecead9ab148a5520dca139b to master...

**Pull request merged**
