### PR TITLE
add "rt" feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 44bebb2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 44bebb2a02314e575b7dd9410158cdf977803e11 with merge abb50aee40239676067657d7e4c46de19031a133...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x-hal/builds/331156142?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 768bdfb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 768bdfb711f4e39e0d89346977b6caeebd45dcee with merge e9ac8ba677977201eec39dc7cb84e6b6b8f07c09...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-hal/builds/331157568?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e9ac8ba677977201eec39dc7cb84e6b6b8f07c09 to master...

**Pull request merged**
