### PR TITLE
add ci

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 79bd48f has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit df7b0b3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit df7b0b32073f8c4be0ec60b4454aa0232a0234af with merge 0f378264262b0b05e0d58744e16b3c5fbebc671c...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1eb35fd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1eb35fd4b63f4bc12f174c903e3468961fae0701 with merge 336d4294b090ed02468dd7084f3bedd529941a97...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e4c622a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e4c622a82bd219efbc11445847aa39c4bcae2f18 with merge 371c2fa70790f433a7cb2144b406afd6a360b003...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b984ce5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b984ce51581c79943cf7ec31fbfc80dd2d61eafd with merge d6176d4d41e874e62dda07e67ed2308e242c1689...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x-hal/builds/328277331?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d6176d4d41e874e62dda07e67ed2308e242c1689 to master...

**Pull request merged**
